[package]
name = "bootlick"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7", optional = true }

[dev-dependencies]
embassy-futures = "0.1.1"

[features]
default = ["cortex_m"]
cortex_m = ["dep:cortex-m"]