variants = ["bootloader", "application"]

[disk]
size = 0x20000
alignment = 0x800

[partitions]
bootloader = { offset = 0x0, size = 0x8000, access = { any = "ro" } }
slot_primary = { offset = 0x8000, size = 0x18000, access = { bootloader = "rw", application = "ro" } }
